"""empty message

Revision ID: 01cbde20a1af
Revises: 2fa90b1b990b
Create Date: 2021-05-10 18:28:55.267430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cbde20a1af'
down_revision = '2fa90b1b990b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta_qresponse', sa.Column('courseID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ta_qresponse', 'courses', ['courseID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ta_qresponse', type_='foreignkey')
    op.drop_column('ta_qresponse', 'courseID')
    # ### end Alembic commands ###
