"""empty message

Revision ID: 2dc1b76a83ab
Revises: 697339c480e2
Create Date: 2021-04-15 16:56:45.223789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc1b76a83ab'
down_revision = '697339c480e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='pa_qresponse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'pa_qresponse', ['username'], unique=True)
    # ### end Alembic commands ###
