"""empty message

Revision ID: 2fa90b1b990b
Revises: 337986a6374a
Create Date: 2021-05-07 14:03:32.728689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa90b1b990b'
down_revision = '337986a6374a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ta_qresponse', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ta_qresponse', 'age')
    # ### end Alembic commands ###
