"""empty message

Revision ID: 337986a6374a
Revises: 6cb7440a4851
Create Date: 2021-04-23 12:49:34.596835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337986a6374a'
down_revision = '6cb7440a4851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('targetUser', table_name='pa_qresponse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('targetUser', 'pa_qresponse', ['targetUser'], unique=True)
    # ### end Alembic commands ###
