"""empty message

Revision ID: d690cf28806a
Revises: 01cbde20a1af
Create Date: 2021-05-10 19:01:33.289687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd690cf28806a'
down_revision = '01cbde20a1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ta_qresponse', 'username',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.create_foreign_key(None, 'ta_qresponse', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ta_qresponse', type_='foreignkey')
    op.alter_column('ta_qresponse', 'username',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
